### ISSUE TITLE
Support for more than one firebase project

### ISSUE THREAD

**Issue by mdziardziel** [saiqulhaq/firebase_dynamic_link#6]
Hi, great work on this gem! 

I have one feature request, for which I prepared branch (with updates specs and readme), but I don't think that I have access rights to push it to your repository.

The main idea is to support for more than one firebase project in one rails app.
Currently api key is configurable once globally

```
    FirebaseDynamicLink.configure do |config|
     ...
      config.api_key = 'API_KEY' # required
     ...
    end
```

my change is to add `api_key` parameter to `FirebaseDynamicLink::Client` constructor.

```
    def initialize(api_key: config.api_key)
      @link_renderer = FirebaseDynamicLink::LinkRenderer.new
      short_links_url = end_point(api_key)
      @connection = FirebaseDynamicLink::Connection.new(short_links_url)
    end
```

after this change user will be able to provide different api key from different firebase project to each `FirebaseDynamicLink::Client` instance.

**Comment by saiqulhaq** [comment]
Currently, it uses Singleton design pattern to make it simple
but yeah, I got your point, I have been involved in a project that require me to set up custom instances for each entity

your proposed code above looks good, please create a PR, and let's see the unit test result

**Comment by mdziardziel** [comment]
I am not able to push branch to your repo

```
ERROR: Permission to saiqulhaq/firebase_dynamic_link.git denied to mdziardziel.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

maybe you can switch something in repository settings?

**Comment by saiqulhaq** [comment]
you should fork my repo first, push the commit to your repo and create Github PR to my repo
maybe this post will help https://opensource.com/article/19/7/create-pull-request-github

**Comment by mdziardziel** [comment]
@saiqulhaq  Thanks for this advice and sorry for delay!  My PR is ready  https://github.com/saiqulhaq/firebase_dynamic_link/pull/7. Please check  if my change looks good
